### ISSUE TITLE
upgrade needed to work with MDAnalysis 0.11.0?

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/PSAnalysisTutorial#2]
The new [MDAnalysis release 0.11.0](https://github.com/MDAnalysis/mdanalysis/wiki/ReleaseNotes0110) breaks parts of the API and it is possible that the _PSAnalysisTutorial_ needs to be [migrated](https://github.com/MDAnalysis/mdanalysis/wiki/MDAnalysis-0.11-unifying-release-user-guide) and pinned to MDAnalysis >= 0.11.0.

**Comment by sseyler** [comment]
The README will need to be updated to reflect the changes to the PSA module, which should be part of the next MDAnalysis release. PSAnalysisTutorial is compatible with the API changes to [MDAnalysis  0.11.0](https://github.com/MDAnalysis/mdanalysis/wiki/ReleaseNotes0110), although it will not be fully compatible with the current version of PSA (that came along with release 0.10.0).

**Comment by sseyler** [comment]
Updated to work with MDAnalysis core components for release >= 0.11.0; fully tested and working with 0.11.1-dev.
