### ISSUE TITLE
add preliminary PLoS Comp Biol citation

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/PSAnalysisTutorial#7]
We already have a DOI for the accepted manuscript: 10.1371/journal.pcbi.1004568 so we should make our citations as close to final as possible:

SL Seyler, A Kumar, MF Thorpe, O Beckstein. Path Similarity Analysis: a Method for Quantifying Macromolecular Pathways. PLoS Comp Biol (2015). doi: 10.1371/journal.pcbi.1004568 (also: arXiv:1505.04807 [q-bio.QM])

**Comment by orbeckst** [comment]
... and make a v2.1 release ;-)

**Comment by sseyler** [comment]
Will add the follow formatted citation (conforms to current PLoS Comput Biol formatting) for release v2.1:

Seyler SL, Kumar A, Thorpe MF, Beckstein O (2015) Path Similarity Analysis: a Method for Quantifying Macromolecular Pathways. PLoS Comput Biol. doi: 10.1371/journal.pcbi.1004568 (also: arXiv:1505.04807 [q-bio.QM])
