### ISSUE TITLE
update zenodo badge with LATEST badge

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/PSAnalysisTutorial#8]
Use the following code to **always display the latest DOI**:

``` rest
.. |zenodo| image:: https://zenodo.org/badge/13219/Becksteinlab/PSAnalysisTutorial.svg
   :target: https://zenodo.org/badge/latestdoi/13219/Becksteinlab/PSAnalysisTutorial
```

Should look like:

[![DOI](https://zenodo.org/badge/13219/Becksteinlab/PSAnalysisTutorial.svg)](https://zenodo.org/badge/latestdoi/13219/Becksteinlab/PSAnalysisTutorial)

**Comment by orbeckst** [comment]
(For some reason, the test badge above still shows the DOI from v1.0 but the link points correctly to the v2.0.)

**Comment by sseyler** [comment]
Updated README with the above code; checked that badge points to v2.0. Will have to update again if necessary to display new DOI (if it doesn't fix itself automatically).
